"""Add timestamp to Post model

Revision ID: f101b0a425bf
Revises: 6439a46af903
Create Date: 2026-01-31 07:31:10.513017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f101b0a425bf'
down_revision = '6439a46af903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
